# Docs: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'github-actions'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      regular:
        update-types:
          - 'patch'
          - 'minor'
      eslint:
        update-types:
          - 'major'
        patterns:
          - 'eslint'
          - '@eslint/*'
      commitlint:
        patterns:
          - '@commitlint/*'
    labels:
      - 'dependencies'
    versioning-strategy: increase
